modLoader="javafml"

loaderVersion="*" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL3"
issueTrackerURL="https://github.com/ToroCraft/ToroHealth/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="torohealth"
version="${file.jarVersion}"
displayName="ToroHealth"
displayURL="https://www.curseforge.com/minecraft/mc-mods/torohealth-damage-indicators" #optional
authors="ToroCraft"
description='''
  Health bars will appear in the top left corner for the entity in the player's crosshairs.
  '''

[[dependencies.torohealth]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="CLIENT"

[[dependencies.torohealth]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.1,)"
ordering="NONE"
side="CLIENT"
